### ISSUE TITLE
Persian Hershey Font

### ISSUE THREAD

**Issue by mkeyno** [VirToReal/Hardy-Hershey-Text#1]
hi , sorry to open ticket for my question , do you know instruction or software to convert specific fonts (Persian ) to Hershey fonts?

**Comment by VirToReal** [comment]
There are quite a few programs which alter the font format into svg. But... Each letter has to be in the correct width and length, and it specific start and end. I made the standard font by hand. The creator of Hershey fonts had it more easily, because many font were already provided by a open source cad program which could be adapted in one row. But he also had to define their dimensions.

In the end... Sorry, no program to just make harshey fonts ;-)

**Comment by mkeyno** [comment]
actually I use GRBL-plotter for my diy cnc cutter , this software is open source and easily can convert a text to G-code , however I found that to support new font , hershey font should be installed , but according to some comment that I've received yet it is not easy as it should be
can you advise me for any possible method ?

**Comment by VirToReal** [comment]
hershey fonts are no true SVG, they're just points which draws a line and creating a font limited in its resolution. The magic is just that the plotter / engraver etc. have to follow these points. The result are fonts who just have to be followed once (good for engravings for example). I think what you need are just the outline of your wished font. 

The easiest way for that would be:
- Create your Textes with Inkscape (Very good and mighty SVG-Software)
- Use pycam to convert the SVG to G-Code (http://pycam.sourceforge.net/) You can select the outline of the svg in the Settings if I remember correctly.

If you use any 3D-Printer Firmware on your DIY CNC Cutter, you might better use my converter to adapt the G-Code to Marlin/Sprinter understandable G-Code. 

Sorry I'm limited here right now, I'm not at home until January. Hope it will work out for you somehow with these hints.
